application: devtusita
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

